# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Learning Diary
  items:
    - label: 'Education Diary'
      link: '/diary/diary'
    - label: 'Learning Objectives'
      link: '/diary/learning'
    - label: 'Skills and Capabilities'
      link: '/diary/skills'
    - label: 'My Projects'
      link: '/diary/projects'
- label: Blockchain
  items:
    - label: 'Blockchain Basics'
      link: '/blockchain/basics'
    - label: 'Non-Fungible Tokens'
      link: '/blockchain/nfts'
    - label: 'Crypto Arbitrage'
      link: '/blockchain/arbitrage'
    - label: 'Ethereum Programming'
      link: '/blockchain/ethereum'
    - label: 'Resources'
      link: '/blockchain/resources'
- label: MERN
  items:
    - label: 'MongoDB'
      link: '/mern/mongo'
    - label: 'Node and Express'
      link: '/mern/nodeExprss'
    - label: 'React'
      link: '/mern/react'
    - label: 'Resources'
      link: '/mern/resources'
- label: Product Management
  items:
    - label: 'Introduction'
      link: '/productmgmt/intro'
    - label: 'Product Management'
      link: '/productmgmt/productmanagement'
    - label: 'Community Management'
      link: '/productmgmt/communitymgmt'
    - label: 'Agile'
      link: '/productmgmt/agile'
- label: Progressive Web Apps
  items:
    - label: 'Basics'
      link: '/pwas/basics'
    - label: 'Resources'
      link: '/pwas/resources'
    - label: 'Study'
      link: '/pwas/study'
- label: Security
  items:
    - label: 'Introduction'
      link: '/security/intro'
    - label: 'Ethical Hacking'
      link: '/security/ethicalHacking'
    - label: 'Application Security'
      link: '/security/appSec'
    - label: 'Resources'
      link: '/security/resources'
- label: Usage
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Changelog
      link: /changelog
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
