# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Learning Diary
  items:
    - label: 'Daily Updates'
      link: '/diary/diary'
    - label: 'Objectives'
      link: '/diary/objectives'
    - label: 'Achievements'
      link: '/diary/achievements'
- label: Progressive Web Apps
  items:
    - label: 'Basics'
      link: '/pwas/basics'
    - label: 'Resources'
      link: '/pwas/resources'
- label: Usage
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Changelog
      link: /changelog
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
